// Generated by gencpp from file nlink_parser/LinktrackNodeframe2.msg
// DO NOT EDIT!


#ifndef NLINK_PARSER_MESSAGE_LINKTRACKNODEFRAME2_H
#define NLINK_PARSER_MESSAGE_LINKTRACKNODEFRAME2_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nlink_parser/LinktrackNode2.h>

namespace nlink_parser
{
template <class ContainerAllocator>
struct LinktrackNodeframe2_
{
  typedef LinktrackNodeframe2_<ContainerAllocator> Type;

  LinktrackNodeframe2_()
    : role(0)
    , id(0)
    , local_time(0)
    , system_time(0)
    , stamp()
    , voltage(0.0)
    , pos_3d()
    , eop_3d()
    , vel_3d()
    , angle_3d()
    , quaternion()
    , imu_gyro_3d()
    , imu_acc_3d()
    , nodes()  {
      pos_3d.assign(0.0);

      eop_3d.assign(0.0);

      vel_3d.assign(0.0);

      angle_3d.assign(0.0);

      quaternion.assign(0.0);

      imu_gyro_3d.assign(0.0);

      imu_acc_3d.assign(0.0);
  }
  LinktrackNodeframe2_(const ContainerAllocator& _alloc)
    : role(0)
    , id(0)
    , local_time(0)
    , system_time(0)
    , stamp()
    , voltage(0.0)
    , pos_3d()
    , eop_3d()
    , vel_3d()
    , angle_3d()
    , quaternion()
    , imu_gyro_3d()
    , imu_acc_3d()
    , nodes(_alloc)  {
  (void)_alloc;
      pos_3d.assign(0.0);

      eop_3d.assign(0.0);

      vel_3d.assign(0.0);

      angle_3d.assign(0.0);

      quaternion.assign(0.0);

      imu_gyro_3d.assign(0.0);

      imu_acc_3d.assign(0.0);
  }



   typedef uint8_t _role_type;
  _role_type role;

   typedef uint8_t _id_type;
  _id_type id;

   typedef uint32_t _local_time_type;
  _local_time_type local_time;

   typedef uint32_t _system_time_type;
  _system_time_type system_time;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef float _voltage_type;
  _voltage_type voltage;

   typedef boost::array<float, 3>  _pos_3d_type;
  _pos_3d_type pos_3d;

   typedef boost::array<float, 3>  _eop_3d_type;
  _eop_3d_type eop_3d;

   typedef boost::array<float, 3>  _vel_3d_type;
  _vel_3d_type vel_3d;

   typedef boost::array<float, 3>  _angle_3d_type;
  _angle_3d_type angle_3d;

   typedef boost::array<float, 4>  _quaternion_type;
  _quaternion_type quaternion;

   typedef boost::array<float, 3>  _imu_gyro_3d_type;
  _imu_gyro_3d_type imu_gyro_3d;

   typedef boost::array<float, 3>  _imu_acc_3d_type;
  _imu_acc_3d_type imu_acc_3d;

   typedef std::vector< ::nlink_parser::LinktrackNode2_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::nlink_parser::LinktrackNode2_<ContainerAllocator> >::other >  _nodes_type;
  _nodes_type nodes;





  typedef boost::shared_ptr< ::nlink_parser::LinktrackNodeframe2_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nlink_parser::LinktrackNodeframe2_<ContainerAllocator> const> ConstPtr;

}; // struct LinktrackNodeframe2_

typedef ::nlink_parser::LinktrackNodeframe2_<std::allocator<void> > LinktrackNodeframe2;

typedef boost::shared_ptr< ::nlink_parser::LinktrackNodeframe2 > LinktrackNodeframe2Ptr;
typedef boost::shared_ptr< ::nlink_parser::LinktrackNodeframe2 const> LinktrackNodeframe2ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nlink_parser::LinktrackNodeframe2_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nlink_parser::LinktrackNodeframe2_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nlink_parser::LinktrackNodeframe2_<ContainerAllocator1> & lhs, const ::nlink_parser::LinktrackNodeframe2_<ContainerAllocator2> & rhs)
{
  return lhs.role == rhs.role &&
    lhs.id == rhs.id &&
    lhs.local_time == rhs.local_time &&
    lhs.system_time == rhs.system_time &&
    lhs.stamp == rhs.stamp &&
    lhs.voltage == rhs.voltage &&
    lhs.pos_3d == rhs.pos_3d &&
    lhs.eop_3d == rhs.eop_3d &&
    lhs.vel_3d == rhs.vel_3d &&
    lhs.angle_3d == rhs.angle_3d &&
    lhs.quaternion == rhs.quaternion &&
    lhs.imu_gyro_3d == rhs.imu_gyro_3d &&
    lhs.imu_acc_3d == rhs.imu_acc_3d &&
    lhs.nodes == rhs.nodes;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nlink_parser::LinktrackNodeframe2_<ContainerAllocator1> & lhs, const ::nlink_parser::LinktrackNodeframe2_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nlink_parser

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nlink_parser::LinktrackNodeframe2_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlink_parser::LinktrackNodeframe2_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nlink_parser::LinktrackNodeframe2_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nlink_parser::LinktrackNodeframe2_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlink_parser::LinktrackNodeframe2_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlink_parser::LinktrackNodeframe2_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nlink_parser::LinktrackNodeframe2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6b5a7e5081758c08a899c751b28eb5ce";
  }

  static const char* value(const ::nlink_parser::LinktrackNodeframe2_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6b5a7e5081758c08ULL;
  static const uint64_t static_value2 = 0xa899c751b28eb5ceULL;
};

template<class ContainerAllocator>
struct DataType< ::nlink_parser::LinktrackNodeframe2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nlink_parser/LinktrackNodeframe2";
  }

  static const char* value(const ::nlink_parser::LinktrackNodeframe2_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nlink_parser::LinktrackNodeframe2_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 role\n"
"uint8 id\n"
"uint32 local_time\n"
"uint32 system_time\n"
"time   stamp\n"
"float32 voltage\n"
"float32[3] pos_3d\n"
"float32[3] eop_3d\n"
"float32[3] vel_3d\n"
"float32[3] angle_3d\n"
"float32[4] quaternion\n"
"float32[3] imu_gyro_3d\n"
"float32[3] imu_acc_3d\n"
"LinktrackNode2[] nodes\n"
"\n"
"================================================================================\n"
"MSG: nlink_parser/LinktrackNode2\n"
"uint8 role\n"
"uint8 id\n"
"float32 dis\n"
"float32 fp_rssi\n"
"float32 rx_rssi\n"
;
  }

  static const char* value(const ::nlink_parser::LinktrackNodeframe2_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nlink_parser::LinktrackNodeframe2_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.role);
      stream.next(m.id);
      stream.next(m.local_time);
      stream.next(m.system_time);
      stream.next(m.stamp);
      stream.next(m.voltage);
      stream.next(m.pos_3d);
      stream.next(m.eop_3d);
      stream.next(m.vel_3d);
      stream.next(m.angle_3d);
      stream.next(m.quaternion);
      stream.next(m.imu_gyro_3d);
      stream.next(m.imu_acc_3d);
      stream.next(m.nodes);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LinktrackNodeframe2_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nlink_parser::LinktrackNodeframe2_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nlink_parser::LinktrackNodeframe2_<ContainerAllocator>& v)
  {
    s << indent << "role: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.role);
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "local_time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.local_time);
    s << indent << "system_time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.system_time);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "voltage: ";
    Printer<float>::stream(s, indent + "  ", v.voltage);
    s << indent << "pos_3d[]" << std::endl;
    for (size_t i = 0; i < v.pos_3d.size(); ++i)
    {
      s << indent << "  pos_3d[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pos_3d[i]);
    }
    s << indent << "eop_3d[]" << std::endl;
    for (size_t i = 0; i < v.eop_3d.size(); ++i)
    {
      s << indent << "  eop_3d[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.eop_3d[i]);
    }
    s << indent << "vel_3d[]" << std::endl;
    for (size_t i = 0; i < v.vel_3d.size(); ++i)
    {
      s << indent << "  vel_3d[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.vel_3d[i]);
    }
    s << indent << "angle_3d[]" << std::endl;
    for (size_t i = 0; i < v.angle_3d.size(); ++i)
    {
      s << indent << "  angle_3d[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.angle_3d[i]);
    }
    s << indent << "quaternion[]" << std::endl;
    for (size_t i = 0; i < v.quaternion.size(); ++i)
    {
      s << indent << "  quaternion[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.quaternion[i]);
    }
    s << indent << "imu_gyro_3d[]" << std::endl;
    for (size_t i = 0; i < v.imu_gyro_3d.size(); ++i)
    {
      s << indent << "  imu_gyro_3d[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.imu_gyro_3d[i]);
    }
    s << indent << "imu_acc_3d[]" << std::endl;
    for (size_t i = 0; i < v.imu_acc_3d.size(); ++i)
    {
      s << indent << "  imu_acc_3d[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.imu_acc_3d[i]);
    }
    s << indent << "nodes[]" << std::endl;
    for (size_t i = 0; i < v.nodes.size(); ++i)
    {
      s << indent << "  nodes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::nlink_parser::LinktrackNode2_<ContainerAllocator> >::stream(s, indent + "    ", v.nodes[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NLINK_PARSER_MESSAGE_LINKTRACKNODEFRAME2_H
