// Generated by gencpp from file nlink_parser/LinktrackTag.msg
// DO NOT EDIT!


#ifndef NLINK_PARSER_MESSAGE_LINKTRACKTAG_H
#define NLINK_PARSER_MESSAGE_LINKTRACKTAG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nlink_parser
{
template <class ContainerAllocator>
struct LinktrackTag_
{
  typedef LinktrackTag_<ContainerAllocator> Type;

  LinktrackTag_()
    : role(0)
    , id(0)
    , pos_3d()
    , dis_arr()  {
      pos_3d.assign(0.0);

      dis_arr.assign(0.0);
  }
  LinktrackTag_(const ContainerAllocator& _alloc)
    : role(0)
    , id(0)
    , pos_3d()
    , dis_arr()  {
  (void)_alloc;
      pos_3d.assign(0.0);

      dis_arr.assign(0.0);
  }



   typedef uint8_t _role_type;
  _role_type role;

   typedef uint8_t _id_type;
  _id_type id;

   typedef boost::array<float, 3>  _pos_3d_type;
  _pos_3d_type pos_3d;

   typedef boost::array<float, 8>  _dis_arr_type;
  _dis_arr_type dis_arr;





  typedef boost::shared_ptr< ::nlink_parser::LinktrackTag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nlink_parser::LinktrackTag_<ContainerAllocator> const> ConstPtr;

}; // struct LinktrackTag_

typedef ::nlink_parser::LinktrackTag_<std::allocator<void> > LinktrackTag;

typedef boost::shared_ptr< ::nlink_parser::LinktrackTag > LinktrackTagPtr;
typedef boost::shared_ptr< ::nlink_parser::LinktrackTag const> LinktrackTagConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nlink_parser::LinktrackTag_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nlink_parser::LinktrackTag_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nlink_parser::LinktrackTag_<ContainerAllocator1> & lhs, const ::nlink_parser::LinktrackTag_<ContainerAllocator2> & rhs)
{
  return lhs.role == rhs.role &&
    lhs.id == rhs.id &&
    lhs.pos_3d == rhs.pos_3d &&
    lhs.dis_arr == rhs.dis_arr;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nlink_parser::LinktrackTag_<ContainerAllocator1> & lhs, const ::nlink_parser::LinktrackTag_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nlink_parser

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nlink_parser::LinktrackTag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nlink_parser::LinktrackTag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nlink_parser::LinktrackTag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nlink_parser::LinktrackTag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlink_parser::LinktrackTag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nlink_parser::LinktrackTag_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nlink_parser::LinktrackTag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a4bf3020fbef59e2422a9233d276302";
  }

  static const char* value(const ::nlink_parser::LinktrackTag_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a4bf3020fbef59eULL;
  static const uint64_t static_value2 = 0x2422a9233d276302ULL;
};

template<class ContainerAllocator>
struct DataType< ::nlink_parser::LinktrackTag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nlink_parser/LinktrackTag";
  }

  static const char* value(const ::nlink_parser::LinktrackTag_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nlink_parser::LinktrackTag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 role\n"
"uint8 id\n"
"float32[3] pos_3d\n"
"float32[8] dis_arr\n"
;
  }

  static const char* value(const ::nlink_parser::LinktrackTag_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nlink_parser::LinktrackTag_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.role);
      stream.next(m.id);
      stream.next(m.pos_3d);
      stream.next(m.dis_arr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LinktrackTag_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nlink_parser::LinktrackTag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nlink_parser::LinktrackTag_<ContainerAllocator>& v)
  {
    s << indent << "role: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.role);
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "pos_3d[]" << std::endl;
    for (size_t i = 0; i < v.pos_3d.size(); ++i)
    {
      s << indent << "  pos_3d[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pos_3d[i]);
    }
    s << indent << "dis_arr[]" << std::endl;
    for (size_t i = 0; i < v.dis_arr.size(); ++i)
    {
      s << indent << "  dis_arr[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.dis_arr[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NLINK_PARSER_MESSAGE_LINKTRACKTAG_H
